In [3]:
import random
import numpy as np

transaction_type = ['l','d']
transactions = []
n = 0
def inputFunction(input):
  global transactions
  global n
  with open('input.txt', 'r') as file:
      lines = file.readlines()
      n = int(lines[0])
      for i in range(1, n+1):
          t, s = lines[i].split()
          transactions.append((t, int(s)))
      return transactions

inputFunction('input.txt')

reg = []
for i in transactions:
  reg.append(i)


print('Register:',reg)

def fitnessFunc(register):  ### it Works!!!!

  sum = 0
  for i in register:
    if i[0] == 'd':
      sum += i[1]
      # print('deposit')
      # print(transaction[1])
    elif i[0] == 'l':
      # print('lent')
      # print(transaction[1])

      sum -= i[1]
    # if sum == 0:
    #     return len(register) - register.count(('z', 0))
    # else:
    #     return 0
  return sum


inputFunction('input.txt')
cashList = []
print('Fitness calculation:',fitnessFunc(reg))

#print('end')

chromosome = []
for i in reg:
  if i[0] == 'd':
    chromosome.append(i[1])
  else:
    chromosome.append(i[1]*-1)


print('Chromosome:',chromosome)
child1 = []
#child2 = []

def crossover(parent):
  global child1
  crossoverPoint = random.randint(1, len(parent)-1)
  firstHalf = parent[:crossoverPoint]
  secondHalf = parent[crossoverPoint:]

# concatenate the two parts in reverse order
  child1 = secondHalf + firstHalf
  return child1


  
print('Crossover:',crossover(chromosome))

def mutate(x):
    max_val = max(x)
    #print('Max',max_val)
    random_index = random.randrange(0, len(x))
    mutation = random.randint(0,max_val)
    for i in range(0, max_val+1):
      count = 0
      if count == 0:
        x[random_index] = mutation
        count += 1
      else:
        break
    return x

muT = mutate(child1)
print('mutated chromosome after crossover:',muT)

column = n
row = column
minimum = min(chromosome)
maximum = max(chromosome)

#### Genetic Algorithm  
randomPopulace = np.random.randint(minimum, maximum, (row, column))

print('Randomly Generated Registers:')
print(randomPopulace)



Register: [('l', 120), ('l', 289), ('d', 475), ('l', 195), ('d', 6482), ('l', 160), ('d', 935)]
Fitness calculation: 7128
Chromosome: [-120, -289, 475, -195, 6482, -160, 935]
Crossover: [475, -195, 6482, -160, 935, -120, -289]
mutated chromosome after crossover: [475, -195, 6482, -160, 1763, -120, -289]
Randomly Generated Registers:
[[ 635 6199 3873 1262 6481 2213 1853]
 [1408 2921 -188 2981 1277 1306 5952]
 [1862 5811 2943 -261 1937 5417 2083]
 [1351 3542 4843 5522 3949 2756 6332]
 [6432 2628  269 4337 5895 1118 3347]
 [2087 6252 6201 4694 1624  577 2012]
 [4356 5788 5236 4218 6401 3365  248]]
