In [81]:
import random

matrice = []
transaction_type = ['l','d']
def inputFunction(input):
    global matrice
    with open('input.txt', 'r') as file:
        lines = file.readlines()
        n = int(lines[0])
        matrice = []
        for i in range(1, n+1):
            t, s = lines[i].split()
            matrice.append((t, int(s)))
        return matrice


inputFunction('input.txt')


chromosome = []

for i in matrice:
    if i[0] == 'l':
        chromosome.append(-1)
    else:
        chromosome.append(1)
print(chromosome)



[-1, -1, 1, -1, 1, -1, 1]


In [117]:
import numpy as np
from array import *
import random
from numpy.random.mtrand import randint


goalTransaction = 0

matrice = []                   # 2D matrix that will read the file
populace = []                     # 1D list of integers gotten by manipulating the first 2D matrix


# ============================== reading text file and inputting in the matrix ===========================

# file = open('input.txt', mode = 'r')
# lines = file.readlines()
# print(lines)
# for line in lines:
#     matrice.append(line.split())
#     print('....')
#     print(line)
transaction = 0
def inputFunction(input):
    with open('input.txt', 'r') as file:
        global transaction
        transaction = int(file.readline())
        print(transaction)
        lines = file.readlines()
        # n = int(lines[0])
        global matrice
        for i in range(0, transaction):
            t, s = lines[i].split()
            matrice.append([t, int(s)])
        return matrice
inputFunction('input.txt')
print("Input : ", matrice)

# transaction = matrice[0]
column = transaction                   # number of transactions
i = column ## 7x7 matrice       

######### 


#### Creating a register that holds a record of the cash flow, outgoing and incoming. It's a 1D array

for i in range(len(matrice)):        # we don't need the column because l or d sits on the first index
    if matrice[i][0] == 'l':         # if the amount was being lend
        populace.append(int(-1 * matrice[i][1]))  # we consider lend as negative
    elif matrice[i][0] == 'd':       # if the amount was being deposited
        populace.append(int(+1 * matrice[i][1]))  # we consider deposit as positive
print("Values : ", populace)

#### Creating a random population of 1's and 0's in matrix that has the number of transactions as the rows and columns


randomPopulace = np.random.randint(0, 2, (i, column))  ###Generate 7 rows, and 7 columns randomly of 0 and 1
print(randomPopulace) 
# populace = randomPopulace
# print(populace)



7
Input :  [['l', 120], ['l', 289], ['d', 475], ['l', 195], ['d', 6482], ['l', 160], ['d', 935]]
Values :  [-120, -289, 475, -195, 6482, -160, 935]
[[1 0 0 0 0 0 0]
 [1 0 1 0 0 1 1]
 [1 1 0 0 0 1 0]
 [0 1 1 0 0 0 0]
 [0 1 0 1 1 1 1]
 [1 0 0 1 1 0 1]]


In [28]:
file = open('input.txt', mode = 'r')

### Transaction register function, under construciton

numOfTransactions = file.readline()

print(numOfTransactions)
#print(file.readlines())
sampArray = []

for i in file.readlines():
  sampArray.append(i.strip())
#for i in sampArray:

print(sampArray)

7

['l 120', 'l 289', 'd 475', 'l 195', 'd 6482', 'l 160', 'd 935']


In [106]:
import random


transaction_type = ['l','d']
def inputFunction(input):
    with open('input.txt', 'r') as file:
        lines = file.readlines()
        n = int(lines[0])
        transactions = []
        for i in range(1, n+1):
            t, s = lines[i].split()
            transactions.append([t, int(s)])
        return transactions
print('aadada')
print(inputFunction('input.txt'))
def fitnessFunc(register):

    sum = 0
    for transaction in register:
        if transaction[0] == 'd':
            sum += transaction[1]
        elif transaction[0] == 'l':
            sum -= transaction[1]
    if sum == 0:
        return len(register) - register.count(('z', 0))
    else:
        return 0

child1 = []
child2 = []
def crossover(p1, p2):  #p1 = p1, p2= parent2
    # global child1
    # global child2
    if len(p1) != len(p2):
        return f'Both parents must be equal in length!'
         
    else:
        length = len(p1)
        crossoverPoint = random.randint(1,length-1)
        global child1, child2
        child1 = p1[:crossoverPoint] + p2[crossoverPoint:]
        child2 = p2[:crossoverPoint] + p1[crossoverPoint:]
        return child1, child2
#childvar1 = child1

def mutate(x):
    tempList = list(x)
    digits = sorted(str(x), reverse=True)
    # print(digits[0])
    max_digit = digits[0]
    # print('////')
    # print(type(digits), ' type')
    # print(type(max_digit))
    # print(max_digit)
    # print(len(digits), 'length')

    random_index = random.randrange(0, len(tempList))
    mutation = random.randint(0,int(max_digit))

    
    for i in range(0,int(max_digit)+1): ##choosing a number from 0 to the max number inside the string
        
        count = 0
        if count == 0:
            # tempList = list(max_digit)
            # tempList[random_index] = mutation
            tempList[random_index] = str(mutation)
            count += 1
        else:
            break
    mutatedString = ''.join(tempList)
    return mutatedString
            



#print(mutate(child1))

x,y = '1443', '2526'
zz = crossover(x,y) #Random values for testing   ≈
print('Children BEFORE CROSSOVER:',x,y)

print('Children After crossover:',zz) 
##Function works perfectly
### Now apply the crossover function to the question

### For mutation

child1_int = int(child1)

child2_int = int(child2)


##find highest number in a child:

# digits = sorted(str(x), reverse=True)
# print(digits[0])
print('Child BEFORE mutation:',child1_int)
muT = mutate(child1)

print('Child AFTER mutation:',muT)
# print(type(child1_int))

###Mutation works, now convert that list of characters to a string



print(type(child1))
transaction = inputFunction('input.txt')
print(transaction)

aadada
[['l', 120], ['l', 289], ['d', 475], ['l', 195], ['d', 6482], ['l', 160], ['d', 935]]
Children BEFORE CROSSOVER: 1443 2526
Children After crossover: ('1526', '2443')
Child BEFORE mutation: 1526
Child AFTER mutation: 1522
<class 'str'>
[['l', 120], ['l', 289], ['d', 475], ['l', 195], ['d', 6482], ['l', 160], ['d', 935]]


In [43]:
import random

def parse_input(filename):
    with open(filename, 'r') as file:
        lines = file.readlines()
        n = int(lines[0])
        transactions = []
        for i in range(1, n+1):
            t, s = lines[i].split()
            transactions.append((t, int(s)))
        return transactions

def fitness(register):
    # Calculate the sum of non-zero elements in the register
    return sum([s for t, s in register if s != 0])

def crossover(parent1, parent2):
    # Perform single-point crossover
    n = len(parent1)
    crossover_point = random.randint(1, n-1)
    child1 = parent1[:crossover_point] + parent2[crossover_point:]
    child2 = parent2[:crossover_point] + parent1[crossover_point:]
    return child1, child2

def mutate(register, mutation_rate):
    # Randomly change some elements in the register
    for i in range(len(register)):
        if random.random() < mutation_rate:
            t, s = register[i]
            if t == 'l':
                s = -s
            register[i] = ('d', s)
    return register

def generate_random_register(n):
    # Generate a random register with n transactions
    register = []
    for i in range(n):
        t = random.choice(['l', 'd'])
        s = random.randint(1, 100000)
        if t == 'l':
            s = -s
        register.append((t, s))
    return register

def find_zero_balance_register(transactions, population_size=100, elite_size=10, mutation_rate=0.01, num_generations=1000):
    # Initialize the population with random registers
    population = [generate_random_register(len(transactions)) for i in range(population_size)]

    # Iterate over generations
    for generation in range(num_generations):
        # Evaluate the fitness of each register in the population
        fitnesses = [fitness(register) for register in population]

        # Find the elite registers with highest fitness
        elite_indices = sorted(range(population_size), key=lambda i: fitnesses[i], reverse=True)[:elite_size]
        elite_registers = [population[i] for i in elite_indices]

        # Select parents for crossover using roulette wheel selection
        fitness_sum = sum(fitnesses)
        parent_probabilities = [fitness / fitness_sum for fitness in fitnesses]
        parents = [random.choices(population, weights=parent_probabilities, k=2) for i in range(population_size - elite_size)]

        # Perform crossover and mutation to generate offspring
        offspring = []
        for i in range(population_size - elite_size):
            child1, child2 = crossover(parents[i][0], parents[i][1])
            offspring.append(mutate(child1, mutation_rate))
            offspring.append(mutate(child2, mutation_rate))

        # Replace the old population with the new population (elite + offspring)
        population = elite_registers + offspring

        # Check if any register balances out to zero
        for register in population:
            if fitness(register) == 0:
                return ''.join(['1' if s != 0 else '0' for t, s in register])

    # If no register balances out to zero, return -1
    return '-1'

# Example usage:
transactions = parse_input('input.txt')
result = find_zero_balance_register(transactions)
print(result)


-1


In [114]:
import numpy as np
from array import *
import random
from numpy.random.mtrand import randint

graph_matrix = []                   # 2D matrix that will read the file
population = []                     # 1D list of integers gotten by manipulating the first 2D matrix


# ============================== reading text file and inputting in the matrix ===========================

with open("input.txt", 'r') as f:
    lines = f.readlines()
for line in lines:
    graph_matrix.append(line.split())
print("Input : ", graph_matrix)
z = graph_matrix[0]
col = int(z[0])                     # number of transactions
row = col                           # number of individuals per Generation

# ============================== converting matrix to 1D suitable model ==================================

for row in range(len(graph_matrix)):        # we don't need the column because l or d sits on the first index
    if graph_matrix[row][0] == 'l':         # if the amount was being lend
        population.append(-1 * int(graph_matrix[row][1]))  # we consider lend as negative
    elif graph_matrix[row][0] == 'd':       # if the amount was being deposited
        population.append(int(+1 * graph_matrix[row][1]))  # we consider deposit as positive
print("Values : ", population)


# ================================ Creating Random Population  ====================================


weight = 0                                                  # our desired summation of transaction is 0
sample = []
sample_2 = []
sample = population
sample_2 = population
rand_pop = np.random.randint(0, 2, (row, col))              # Generating random population with binary values
print("Randomly Generated Population of Binary numbers, \n Generation - 1 : \n", rand_pop)
rand_pop_temp = np.random.randint(0, 2, (row, col))         # We will use this later to build the next Generation
summation = np.zeros((row, col))
rand_pop = np.append(rand_pop, summation, axis=1)
peak = 0                                                    # store maximum value
captureIndividual = []                                      # store associated individual


# =========================== Starting iteration and summing up the transactions ========================

for q in range(row):
    for i in range(col):
        addition1 = sum(np.multiply(sample, rand_pop[i, 0:col]))  # Calculating Total sum
        if addition1 == weight:
            captureIndividual = rand_pop[i, 0:col]
            peak = addition1
        rand_pop[i, col] = addition1
        addition2 = sum(np.multiply(sample_2, rand_pop[i, 0:col]))
        if addition2 == weight:
            captureIndividual = rand_pop[i, 0:col]
            peak = addition2
        rand_pop[i, col + 1] = addition2

# ================================= Calculating the fitness ========================================


for i in range(row):
    rand_pop[i, col+2] = rand_pop[i, col+1] / np.average(rand_pop[:, col+1])
    rand_pop[i, col+3] = round(rand_pop[i, col+2])
print("Addition values : \n", rand_pop[:, col:col+4].tolist())
print("Sum : ", sum(rand_pop[:, col+1]))
print("Average for fitness : ", np.average(rand_pop[:, col+1]))


# ======================= Determining number of chromosomes for next generation ======================


count = 0
c = 0
for i in range(row):
    numberOfChromosomes = rand_pop[i, 10]
    count += numberOfChromosomes
    if count > row:
        numberOfChromosomes -= 1
        for j in range(int(numberOfChromosomes)):
            rand_pop_temp = rand_pop[i, 0:col]
            c += 1
rand_pop[:, 0:col] = rand_pop_temp
print("Generation - 2: \n", rand_pop[:, 0:col])


# ============================ Selecting two random indices  ==================================


rand = np.array([])
while 1:
    randomIndex = np.random.randint(low=0, high=row, size=2)
    x, y = np.unique(randomIndex, return_counts=True)
    rand = x[y > 1]
    if rand.size == 0:
        break
print("Selecting two discrete transactions ")


# =========================== Selecting data points of those indices  =============================

f = 0
for i in randomIndex:
    rand_pop_temp[f] = rand_pop[i, 0:col]
    f += 1

# ============================ Determining crossover points  ======================================

a = np.random.randint(low=1, high=col, size=1)
print("Crossover point : ", int(a))
print("Pre-Crossover : \n", rand_pop_temp[0:round(col/2)])
b = []
c = []
b = rand_pop_temp[0, int(a):col].tolist()
c = rand_pop_temp[1, int(a):col].tolist()
rand_pop_temp[1, int(a):col] = b
rand_pop_temp[0, int(a):col] = c
print("Post-Crossover : \n", rand_pop_temp[0:4])


# ====================================  Next Generation   ====================================

d = 0
for i in randomIndex:
    rand_pop[i, 0:col] = rand_pop_temp[d]
    d += 0
print("Generation - 3 Post-Crossover : \n", rand_pop[:, 0:col])


# ====================================   Mutation    =================================================

# Converting 1 to 0 and 0 to 1
random_r = int(np.random.randint(0, row, (1, 1)))
random_c = int(np.random.randint(0, col, (1, 1)))
print("Mutation at position : \n", random_r, " , ", random_c)
rand_pop[random_r, random_c] = 1 - int(rand_pop[random_r, random_c])
print("Post-Mutation :\n", rand_pop[:, 0:col])

# =====================================    Final     =====================================================

for i in range(row):
    rand_pop[i, col+2] = rand_pop[i, int(z[0])+1] / np.average(rand_pop[:col+1])
    rand_pop[i, col+3] = round(rand_pop[i, col+2])
    print(rand_pop[i, col+1:col+2].tolist())

if len(captureIndividual) == 0:
    print("No such pattern found")
elif len(captureIndividual) != 0:
    print(" Pattern  : ", captureIndividual, " the summation : ", peak)

# =========================================================================================================
# def fitness(population, sample):
#     count = 0
#     for r in range(row):
#         for c in range(col):
#         # random_population[r][c] *= population[c]
#         # x += random_population[r][c]
#         # print(x)
#             sum_Population = sum(np.multiply(population[c], sample[r, 0:c]))
#             if sum_Population == 0:
#                 capture_Individual = (sample[r, 0:c])
#             print(capture_Individual)
#             count += 1
#     return count
# # print(fitness(population,sample))
# # Random Selection Function
# def selection(sample):
#     sample.sort(key=lambda x: sample.fitness(x), reverse=True)  # sorting
#     new_population = sample.sort[0:50]
# sample = []
# sample = np.random.randint(0, 2, (row, col))
# print("The Random Population : \n", sample)
# row = col**5  # number of different individuals
# random_population = np.random.randint(0, 2, (row, col))
# print("Generated Random Population : \n", random_population)
# x = 0
# capture_Individual = []
# rand_pop = np.append(rand_pop,addZeros,axis=1)
# print (n)
# print(graph_matrix[1][0])
# test.append(int(graph_matrix[1][1]))
# test[0]=-1*test[0]
# print(graph_matrix[2][0])
# test.append(int(graph_matrix[2][1]))
# test[1]=-1*test[1]
# print(test[0])
# print(test[1])
# if (graph_matrix[row] =='l'):
#     x=row
#     print(row)
# elif(graph_matrix[row] =='d'):
#     test.append(int(graph_matrix[row][1]))

Input :  [['7'], ['l', '120'], ['l', '289'], ['d', '475'], ['l', '195'], ['d', '6482'], ['l', '160'], ['d', '935']]
Values :  [-120, -289, 475, -195, 6482, -160, 935]
Randomly Generated Population of Binary numbers, 
 Generation - 1 : 
 [[0 0 0 1 1 0 0]
 [1 1 0 1 0 0 0]
 [0 0 1 1 1 0 0]
 [1 0 1 0 1 1 1]
 [1 1 0 0 0 1 1]
 [1 1 0 1 0 1 1]
 [1 0 1 0 0 0 0]]
Addition values : 
 [[6287.0, 6287.0, 2.100768533104205, 2.0], [-604.0, -604.0, -0.20182347606090983, 0.0], [6762.0, 6762.0, 2.259487326364027, 2.0], [7612.0, 7612.0, 2.5435104300921285, 3.0], [366.0, 366.0, 0.12229700701704138, 0.0], [171.0, 171.0, 0.05713876557353573, 0.0], [355.0, 355.0, 0.11862141390997183, 0.0]]
Sum :  20949.0
Average for fitness :  2992.714285714286
Generation - 2: 
 [[1. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 0.]
 [1. 0. 1. 0. 0. 1. 0.]
 [1. 0. 1. 1. 1. 0. 1.]
 [0. 1. 1. 0. 1. 1. 0.]
 [1. 0. 0. 1. 1. 1. 0.]
 [1. 0. 0. 1. 0. 0. 0.]]
Selecting two discrete transactions 
Crossover point :  4
Pre-Crossover : 
 [[1 0

In [3]:
import random

# define constants
TRANSACTION_TYPES = ['l', 'd']
MAX_ITERATIONS = 10000
POPULATION_SIZE = 100
MUTATION_PROBABILITY = 0.1


def parse_input(file_path):
    with open(file_path, 'r') as f:
        n = int(f.readline().strip())
        transactions = []
        for i in range(n):
            line = f.readline().strip().split()
            transaction_type = line[0]
            amount = int(line[1])
            #print(amount)
            print(transaction_type)
            if transaction_type == 'l':
                amount = -amount
            transactions.append(amount)
    return transactions

parse_input('input.txt')

# def fitness(register):
#     # compute the sum of the non-zero elements in the register
#     s = 0
#     for transaction in register:
#         if transaction[0] == 'd':
#             s += transaction[1]
#         elif transaction[0] == 'l':
#             s -= transaction[1]
#     return s


# def crossover(parent1, parent2):
#     # perform single-point crossover on the two parents
#     crossover_point = random.randint(1, len(parent1) - 1)
#     child1 = parent1[:crossover_point] + parent2[crossover_point:]
#     child2 = parent2[:crossover_point] + parent1[crossover_point:]
#     return child1, child2


# def mutation(register):
#     # randomly mutate a single transaction in the register
#     mutated_register = register.copy()
#     if random.random() < MUTATION_PROBABILITY:
#         mutation_index = random.randint(0, len(mutated_register) - 1)
#         mutation_type = random.choice(TRANSACTION_TYPES)
#         mutation_amount = random.randint(1, 100000)
#         mutated_register[mutation_index] = (mutation_type, mutation_amount)
#     return mutated_register


# def create_random_register():
#     # create a random register with random transactions
#     register = []
#     for i in range(TRANSACTION_COUNT):
#         transaction_type = random.choice(TRANSACTION_TYPES)
#         transaction_amount = random.randint(1, 100000)
#         register.append((transaction_type, transaction_amount))
#     return register


# def run_genetic_algorithm(transactions):
#     # initialize the population with random registers
#     population = [create_random_register() for i in range(POPULATION_SIZE)]
#     best_register = None
#     best_fitness = float('-inf')
#     iteration = 0
#     while iteration < MAX_ITERATIONS:
#         # evaluate the fitness of each register in the population
#         fitness_scores = [fitness(register) for register in population]

#         # select the two registers with the highest fitness scores as parents for crossover
#         parent1, parent2 = population[fitness_scores.index(max(fitness_scores))], \
#                            population[fitness_scores.index(sorted(fitness_scores)[-2])]

#         # perform crossover and mutation on the parents to create two new children
#         child1, child2 = crossover(parent1, parent2)
#         child1 = mutation(child1)
#         child2 = mutation(child2)

#         # add the children to the population
#         population.extend([child1, child2])

#         # select the new population by keeping only the registers with the highest fitness scores
#         population_fitness = [(register, fitness(register)) for register in population]
#         population_fitness = sorted(population_fitness, key=lambda x: x[1], reverse=True)
#         population = [register for register, score in population_fitness[:POPULATION_SIZE]]

#         # update the best register and best fitness score if necessary
#         if population_fitness[0][1] > best_fitness:
#             best_register = population_fitness[0][0]
           
# transactions= parse_input('input.txt')

# run_genetic_algorithm(transactions)


l
l
d
l
d
l
d


[-120, -289, 475, -195, 6482, -160, 935]